{
 "title": "Real-Time Dashboard - Ride Event Analysis",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Avg. Of Passenger Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg(avg_passenger_count) FROM \"default\".\"flink_sink\" LIMIT 1000"
    }
   ]
  },
  {
   "title": "Avg. of Earning Fare",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg(avg_fare) as avg_fare FROM \"default\".\"flink_sink\""
    }
   ]
  },
  {
   "title": "Avg. Of User Rating",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg(avg_user_rating) as avg_user_rating FROM \"default\".\"flink_sink\""
    }
   ]
  },
  {
   "title": "Avg. of Driver Rating",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg(avg_driver_rating) as avg_driver_rating FROM \"default\".\"flink_sink\""
    }
   ]
  },
  {
   "title": "Avg. Of Completion Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  AVG((completed_count/ride_count) * 100) AS completion_rate\nFROM \n  \"default\".\"flink_sink\""
    }
   ]
  },
  {
   "title": "Avg. Of Cancellation Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  AVG((cancelled_count/ride_count) * 100) AS completion_rate\nFROM \n  \"default\".\"flink_sink\""
    }
   ]
  },
  {
   "title": "Total Completed Ride",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \n  window_start,\n  SUM(completed_count) AS completed_count\nFROM \n  \"default\".\"flink_sink\"\nGROUP BY window_start"
    }
   ]
  },
  {
   "title": "Total Cancelled Ride",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \n  window_start,\n  SUM(cancelled_count) AS cancelled_count\nFROM \n  \"default\".\"flink_sink\"\nGROUP BY window_start"
    }
   ]
  },
  {
   "title": "Total Ride Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT window_start, sum(ride_count) as Total_Ride FROM \"default\".\"flink_sink\" GROUP BY window_start"
    }
   ]
  }
 ]
}